linters:
  disable-all: true
  enable:
  - gosec
  - govet
  - ineffassign
  - misspell
  - errcheck
  - unused
  - gocognit

  # https://github.com/golangci/golangci-lint/pull/2438
  # Disable linter that does not work with go1.18
  #- staticcheck
  #- gosimple

linters-settings:
  gofmt:
    simplify: false
  gosec:
    excludes:
    - G404 # G404: Use of weak random number generator (math/rand instead of crypto/rand)

run:
  go: "1.19"
  timeout: 5m
