version: '2'

services:
  db:
    image: mdillon/postgis:9.5
  redis:
    image: redis:3.0
  app_data:
    image: skygeario/skygear-godev:go1.8
    volumes:
    - /go/pkg
  app:
    image: skygeario/skygear-godev:go1.8
    volumes:
    - .:/go/src/github.com/skygeario/skygear-server
    volumes_from:
    - app_data
    working_dir: /go/src/github.com/skygeario/skygear-server
    links:
    - db
    - redis
    environment:
      DATABASE_URL: postgresql://postgres:@db/postgres?sslmode=disable
      REDISTEST: redis://redis:6379
      PGHOST: db
      PGUSER: postgres
      GOBIN: /go/bin
  db_cmd:
    image: mdillon/postgis:9.5
    links:
    - db
    environment:
      PGHOST: db
      PGUSER: postgres
