// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go

// Package interaction_test is a generated GoMock package.
package interaction_test

import (
	authenticator "github.com/authgear/authgear-server/pkg/auth/dependency/authenticator"
	identity "github.com/authgear/authgear-server/pkg/auth/dependency/identity"
	event "github.com/authgear/authgear-server/pkg/auth/event"
	model "github.com/authgear/authgear-server/pkg/auth/model"
	authn "github.com/authgear/authgear-server/pkg/core/authn"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIdentityProvider is a mock of IdentityProvider interface
type MockIdentityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockIdentityProviderMockRecorder
}

// MockIdentityProviderMockRecorder is the mock recorder for MockIdentityProvider
type MockIdentityProviderMockRecorder struct {
	mock *MockIdentityProvider
}

// NewMockIdentityProvider creates a new mock instance
func NewMockIdentityProvider(ctrl *gomock.Controller) *MockIdentityProvider {
	mock := &MockIdentityProvider{ctrl: ctrl}
	mock.recorder = &MockIdentityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIdentityProvider) EXPECT() *MockIdentityProviderMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockIdentityProvider) Get(userID string, typ authn.IdentityType, id string) (*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userID, typ, id)
	ret0, _ := ret[0].(*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockIdentityProviderMockRecorder) Get(userID, typ, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdentityProvider)(nil).Get), userID, typ, id)
}

// GetByClaims mocks base method
func (m *MockIdentityProvider) GetByClaims(typ authn.IdentityType, claims map[string]interface{}) (string, *identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByClaims", typ, claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*identity.Info)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByClaims indicates an expected call of GetByClaims
func (mr *MockIdentityProviderMockRecorder) GetByClaims(typ, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByClaims", reflect.TypeOf((*MockIdentityProvider)(nil).GetByClaims), typ, claims)
}

// GetByUserAndClaims mocks base method
func (m *MockIdentityProvider) GetByUserAndClaims(typ authn.IdentityType, userID string, claims map[string]interface{}) (*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserAndClaims", typ, userID, claims)
	ret0, _ := ret[0].(*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserAndClaims indicates an expected call of GetByUserAndClaims
func (mr *MockIdentityProviderMockRecorder) GetByUserAndClaims(typ, userID, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserAndClaims", reflect.TypeOf((*MockIdentityProvider)(nil).GetByUserAndClaims), typ, userID, claims)
}

// ListByClaims mocks base method
func (m *MockIdentityProvider) ListByClaims(claims map[string]string) ([]*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByClaims", claims)
	ret0, _ := ret[0].([]*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByClaims indicates an expected call of ListByClaims
func (mr *MockIdentityProviderMockRecorder) ListByClaims(claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByClaims", reflect.TypeOf((*MockIdentityProvider)(nil).ListByClaims), claims)
}

// ListByUser mocks base method
func (m *MockIdentityProvider) ListByUser(userID string) ([]*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", userID)
	ret0, _ := ret[0].([]*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser
func (mr *MockIdentityProviderMockRecorder) ListByUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockIdentityProvider)(nil).ListByUser), userID)
}

// New mocks base method
func (m *MockIdentityProvider) New(userID string, typ authn.IdentityType, claims map[string]interface{}) (*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", userID, typ, claims)
	ret0, _ := ret[0].(*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New
func (mr *MockIdentityProviderMockRecorder) New(userID, typ, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockIdentityProvider)(nil).New), userID, typ, claims)
}

// WithClaims mocks base method
func (m *MockIdentityProvider) WithClaims(ii *identity.Info, claims map[string]interface{}) (*identity.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithClaims", ii, claims)
	ret0, _ := ret[0].(*identity.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WithClaims indicates an expected call of WithClaims
func (mr *MockIdentityProviderMockRecorder) WithClaims(ii, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithClaims", reflect.TypeOf((*MockIdentityProvider)(nil).WithClaims), ii, claims)
}

// CreateAll mocks base method
func (m *MockIdentityProvider) CreateAll(is []*identity.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", is)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll
func (mr *MockIdentityProviderMockRecorder) CreateAll(is interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockIdentityProvider)(nil).CreateAll), is)
}

// UpdateAll mocks base method
func (m *MockIdentityProvider) UpdateAll(is []*identity.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", is)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAll indicates an expected call of UpdateAll
func (mr *MockIdentityProviderMockRecorder) UpdateAll(is interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockIdentityProvider)(nil).UpdateAll), is)
}

// DeleteAll mocks base method
func (m *MockIdentityProvider) DeleteAll(is []*identity.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", is)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll
func (mr *MockIdentityProviderMockRecorder) DeleteAll(is interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockIdentityProvider)(nil).DeleteAll), is)
}

// Validate mocks base method
func (m *MockIdentityProvider) Validate(is []*identity.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", is)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate
func (mr *MockIdentityProviderMockRecorder) Validate(is interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockIdentityProvider)(nil).Validate), is)
}

// RelateIdentityToAuthenticator mocks base method
func (m *MockIdentityProvider) RelateIdentityToAuthenticator(identityInfo *identity.Info, authenticatorSpec *authenticator.Spec) *authenticator.Spec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RelateIdentityToAuthenticator", identityInfo, authenticatorSpec)
	ret0, _ := ret[0].(*authenticator.Spec)
	return ret0
}

// RelateIdentityToAuthenticator indicates an expected call of RelateIdentityToAuthenticator
func (mr *MockIdentityProviderMockRecorder) RelateIdentityToAuthenticator(identityInfo, authenticatorSpec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RelateIdentityToAuthenticator", reflect.TypeOf((*MockIdentityProvider)(nil).RelateIdentityToAuthenticator), identityInfo, authenticatorSpec)
}

// CheckIdentityDuplicated mocks base method
func (m *MockIdentityProvider) CheckIdentityDuplicated(is *identity.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIdentityDuplicated", is)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckIdentityDuplicated indicates an expected call of CheckIdentityDuplicated
func (mr *MockIdentityProviderMockRecorder) CheckIdentityDuplicated(is interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIdentityDuplicated", reflect.TypeOf((*MockIdentityProvider)(nil).CheckIdentityDuplicated), is)
}

// MockAuthenticatorProvider is a mock of AuthenticatorProvider interface
type MockAuthenticatorProvider struct {
	ctrl     *gomock.Controller
	recorder *MockAuthenticatorProviderMockRecorder
}

// MockAuthenticatorProviderMockRecorder is the mock recorder for MockAuthenticatorProvider
type MockAuthenticatorProviderMockRecorder struct {
	mock *MockAuthenticatorProvider
}

// NewMockAuthenticatorProvider creates a new mock instance
func NewMockAuthenticatorProvider(ctrl *gomock.Controller) *MockAuthenticatorProvider {
	mock := &MockAuthenticatorProvider{ctrl: ctrl}
	mock.recorder = &MockAuthenticatorProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAuthenticatorProvider) EXPECT() *MockAuthenticatorProviderMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockAuthenticatorProvider) Get(userID string, typ authn.AuthenticatorType, id string) (*authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userID, typ, id)
	ret0, _ := ret[0].(*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockAuthenticatorProviderMockRecorder) Get(userID, typ, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAuthenticatorProvider)(nil).Get), userID, typ, id)
}

// List mocks base method
func (m *MockAuthenticatorProvider) List(userID string, typ authn.AuthenticatorType) ([]*authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", userID, typ)
	ret0, _ := ret[0].([]*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockAuthenticatorProviderMockRecorder) List(userID, typ interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuthenticatorProvider)(nil).List), userID, typ)
}

// ListByIdentity mocks base method
func (m *MockAuthenticatorProvider) ListByIdentity(userID string, ii *identity.Info) ([]*authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIdentity", userID, ii)
	ret0, _ := ret[0].([]*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIdentity indicates an expected call of ListByIdentity
func (mr *MockAuthenticatorProviderMockRecorder) ListByIdentity(userID, ii interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIdentity", reflect.TypeOf((*MockAuthenticatorProvider)(nil).ListByIdentity), userID, ii)
}

// New mocks base method
func (m *MockAuthenticatorProvider) New(userID string, spec authenticator.Spec, secret string) ([]*authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", userID, spec, secret)
	ret0, _ := ret[0].([]*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New
func (mr *MockAuthenticatorProviderMockRecorder) New(userID, spec, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockAuthenticatorProvider)(nil).New), userID, spec, secret)
}

// WithSecret mocks base method
func (m *MockAuthenticatorProvider) WithSecret(userID string, a *authenticator.Info, secret string) (bool, *authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithSecret", userID, a, secret)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*authenticator.Info)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WithSecret indicates an expected call of WithSecret
func (mr *MockAuthenticatorProviderMockRecorder) WithSecret(userID, a, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithSecret", reflect.TypeOf((*MockAuthenticatorProvider)(nil).WithSecret), userID, a, secret)
}

// CreateAll mocks base method
func (m *MockAuthenticatorProvider) CreateAll(userID string, ais []*authenticator.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAll", userID, ais)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAll indicates an expected call of CreateAll
func (mr *MockAuthenticatorProviderMockRecorder) CreateAll(userID, ais interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAll", reflect.TypeOf((*MockAuthenticatorProvider)(nil).CreateAll), userID, ais)
}

// UpdateAll mocks base method
func (m *MockAuthenticatorProvider) UpdateAll(userID string, ais []*authenticator.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAll", userID, ais)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAll indicates an expected call of UpdateAll
func (mr *MockAuthenticatorProviderMockRecorder) UpdateAll(userID, ais interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAll", reflect.TypeOf((*MockAuthenticatorProvider)(nil).UpdateAll), userID, ais)
}

// DeleteAll mocks base method
func (m *MockAuthenticatorProvider) DeleteAll(userID string, ais []*authenticator.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", userID, ais)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll
func (mr *MockAuthenticatorProviderMockRecorder) DeleteAll(userID, ais interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockAuthenticatorProvider)(nil).DeleteAll), userID, ais)
}

// Authenticate mocks base method
func (m *MockAuthenticatorProvider) Authenticate(userID string, spec authenticator.Spec, state *map[string]string, secret string) (*authenticator.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", userID, spec, state, secret)
	ret0, _ := ret[0].(*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate
func (mr *MockAuthenticatorProviderMockRecorder) Authenticate(userID, spec, state, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockAuthenticatorProvider)(nil).Authenticate), userID, spec, state, secret)
}

// VerifySecret mocks base method
func (m *MockAuthenticatorProvider) VerifySecret(userID string, a *authenticator.Info, secret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySecret", userID, a, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifySecret indicates an expected call of VerifySecret
func (mr *MockAuthenticatorProviderMockRecorder) VerifySecret(userID, a, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySecret", reflect.TypeOf((*MockAuthenticatorProvider)(nil).VerifySecret), userID, a, secret)
}

// MockUserProvider is a mock of UserProvider interface
type MockUserProvider struct {
	ctrl     *gomock.Controller
	recorder *MockUserProviderMockRecorder
}

// MockUserProviderMockRecorder is the mock recorder for MockUserProvider
type MockUserProviderMockRecorder struct {
	mock *MockUserProvider
}

// NewMockUserProvider creates a new mock instance
func NewMockUserProvider(ctrl *gomock.Controller) *MockUserProvider {
	mock := &MockUserProvider{ctrl: ctrl}
	mock.recorder = &MockUserProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUserProvider) EXPECT() *MockUserProviderMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockUserProvider) Create(userID string, metadata map[string]interface{}, identities []*identity.Info, authenticators []*authenticator.Info) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", userID, metadata, identities, authenticators)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockUserProviderMockRecorder) Create(userID, metadata, identities, authenticators interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProvider)(nil).Create), userID, metadata, identities, authenticators)
}

// Get mocks base method
func (m *MockUserProvider) Get(userID string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get
func (mr *MockUserProviderMockRecorder) Get(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserProvider)(nil).Get), userID)
}

// MockOOBProvider is a mock of OOBProvider interface
type MockOOBProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOOBProviderMockRecorder
}

// MockOOBProviderMockRecorder is the mock recorder for MockOOBProvider
type MockOOBProviderMockRecorder struct {
	mock *MockOOBProvider
}

// NewMockOOBProvider creates a new mock instance
func NewMockOOBProvider(ctrl *gomock.Controller) *MockOOBProvider {
	mock := &MockOOBProvider{ctrl: ctrl}
	mock.recorder = &MockOOBProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOOBProvider) EXPECT() *MockOOBProviderMockRecorder {
	return m.recorder
}

// GenerateCode mocks base method
func (m *MockOOBProvider) GenerateCode(channel authn.AuthenticatorOOBChannel) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCode", channel)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateCode indicates an expected call of GenerateCode
func (mr *MockOOBProviderMockRecorder) GenerateCode(channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCode", reflect.TypeOf((*MockOOBProvider)(nil).GenerateCode), channel)
}

// MockHookProvider is a mock of HookProvider interface
type MockHookProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHookProviderMockRecorder
}

// MockHookProviderMockRecorder is the mock recorder for MockHookProvider
type MockHookProviderMockRecorder struct {
	mock *MockHookProvider
}

// NewMockHookProvider creates a new mock instance
func NewMockHookProvider(ctrl *gomock.Controller) *MockHookProvider {
	mock := &MockHookProvider{ctrl: ctrl}
	mock.recorder = &MockHookProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHookProvider) EXPECT() *MockHookProviderMockRecorder {
	return m.recorder
}

// DispatchEvent mocks base method
func (m *MockHookProvider) DispatchEvent(payload event.Payload, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchEvent", payload, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchEvent indicates an expected call of DispatchEvent
func (mr *MockHookProviderMockRecorder) DispatchEvent(payload, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchEvent", reflect.TypeOf((*MockHookProvider)(nil).DispatchEvent), payload, user)
}
