export const ENDPOINT = __ENV.ENDPOINT;
export const CLIENT_ID = __ENV.CLIENT_ID;
export const REDIRECT_URI = __ENV.REDIRECT_URI;
export const FIXTURE_FIXED_OTP = __ENV.FIXTURE_FIXED_OTP;
export const FIXTURE_PASSWORD = __ENV.FIXTURE_PASSWORD;
export const FIXTURE_EMAIL_DOMAIN = __ENV.FIXTURE_EMAIL_DOMAIN;
export const FIXTURE_PHONE_NUMBER_COUNTRY_CALLING_CODE =
  __ENV.FIXTURE_PHONE_NUMBER_COUNTRY_CALLING_CODE;
export const FIXTURE_PHONE_NUMBER_LOW = __ENV.FIXTURE_PHONE_NUMBER_LOW;
export const FIXTURE_PHONE_NUMBER_HIGH = __ENV.FIXTURE_PHONE_NUMBER_HIGH;
