name: Build image
description: "Build image"
inputs:
  dockerfile:
    description: "The path to Dockerfile"
    required: true
  image_name:
    description: "The full image name"
    required: true
  push_image:
    description: "Either 'true' or 'false'"
    required: true
  build_arch:
    description: "Either 'amd64' or 'arm64'"
    required: true
  docker_registry:
    description: "The Docker registry to login to. Required when push_image is 'true'."
    required: false
  docker_username:
    description: "The username to login the Docker registry. Required when push_image is 'true'."
    required: false
  docker_password:
    description: "The password to login the Docker registry. Required when push_image is 'true'."
    required: false
outputs:
  image_digest:
    description: "Something that you can use in `docker buildx imagetools create`"
    value: ${{ steps.build_image.outputs.image_digest }}
runs:
  using: "composite"
  steps:
  - name: Install qemu for multi arch build
    shell: bash
    run: docker run --privileged --rm tonistiigi/binfmt --install all
  - uses: ./.github/actions/docker-buildx-create
  - name: docker login
    if: ${{ inputs.push_image == 'true' }}
    env:
      DOCKER_USERNAME: ${{ inputs.docker_username }}
      DOCKER_PASSWORD: ${{ inputs.docker_password }}
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}
    shell: bash
    run: |
      printf "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" $DOCKER_REGISTRY
  - id: build_image
    env:
      DOCKERFILE: ${{ inputs.dockerfile }}
      IMAGE_NAME: ${{ inputs.image_name }}
      OUTPUT: ${{ (inputs.push_image == 'true') && format('type=image,name={0},push-by-digest=true,name-canonical=true,push=true', inputs.image_name) || '' }}
      BUILD_ARCH: ${{ inputs.build_arch }}
    shell: bash
    run: |
      export METADATA_FILE="$(mktemp).json"
      echo "METADATA_FILE=$METADATA_FILE"
      make build-image
      (set -x && cat "$METADATA_FILE")
      DIGEST="$(jq < "$METADATA_FILE" '.["containerimage.digest"]' -r)"
      echo "image_digest=$DIGEST" >> "$GITHUB_OUTPUT"
  - name: docker logout
    if: ${{ always() }}
    env:
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}
    shell: bash
    run: |
      docker logout $DOCKER_REGISTRY
