// Code generated by MockGen. DO NOT EDIT.
// Source: imageproxy.go

// Package imageproxy is a generated GoMock package.
package imageproxy

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDirector is a mock of Director interface.
type MockDirector struct {
	ctrl     *gomock.Controller
	recorder *MockDirectorMockRecorder
}

// MockDirectorMockRecorder is the mock recorder for MockDirector.
type MockDirectorMockRecorder struct {
	mock *MockDirector
}

// NewMockDirector creates a new mock instance.
func NewMockDirector(ctrl *gomock.Controller) *MockDirector {
	mock := &MockDirector{ctrl: ctrl}
	mock.recorder = &MockDirectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirector) EXPECT() *MockDirectorMockRecorder {
	return m.recorder
}

// Director mocks base method.
func (m *MockDirector) Director(r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Director", r)
}

// Director indicates an expected call of Director.
func (mr *MockDirectorMockRecorder) Director(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Director", reflect.TypeOf((*MockDirector)(nil).Director), r)
}
