// Code generated by MockGen. DO NOT EDIT.
// Source: query.go

// Package skydb is a generated GoMock package.
package skydb

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockFunc is a mock of Func interface
type MockFunc struct {
	ctrl     *gomock.Controller
	recorder *MockFuncMockRecorder
}

// MockFuncMockRecorder is the mock recorder for MockFunc
type MockFuncMockRecorder struct {
	mock *MockFunc
}

// NewMockFunc creates a new mock instance
func NewMockFunc(ctrl *gomock.Controller) *MockFunc {
	mock := &MockFunc{ctrl: ctrl}
	mock.recorder = &MockFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFunc) EXPECT() *MockFuncMockRecorder {
	return m.recorder
}

// Args mocks base method
func (m *MockFunc) Args() []interface{} {
	ret := m.ctrl.Call(m, "Args")
	ret0, _ := ret[0].([]interface{})
	return ret0
}

// Args indicates an expected call of Args
func (mr *MockFuncMockRecorder) Args() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Args", reflect.TypeOf((*MockFunc)(nil).Args))
}

// DataType mocks base method
func (m *MockFunc) DataType() DataType {
	ret := m.ctrl.Call(m, "DataType")
	ret0, _ := ret[0].(DataType)
	return ret0
}

// DataType indicates an expected call of DataType
func (mr *MockFuncMockRecorder) DataType() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataType", reflect.TypeOf((*MockFunc)(nil).DataType))
}

// MockKeyPathFunc is a mock of KeyPathFunc interface
type MockKeyPathFunc struct {
	ctrl     *gomock.Controller
	recorder *MockKeyPathFuncMockRecorder
}

// MockKeyPathFuncMockRecorder is the mock recorder for MockKeyPathFunc
type MockKeyPathFuncMockRecorder struct {
	mock *MockKeyPathFunc
}

// NewMockKeyPathFunc creates a new mock instance
func NewMockKeyPathFunc(ctrl *gomock.Controller) *MockKeyPathFunc {
	mock := &MockKeyPathFunc{ctrl: ctrl}
	mock.recorder = &MockKeyPathFuncMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKeyPathFunc) EXPECT() *MockKeyPathFuncMockRecorder {
	return m.recorder
}

// ReferencedKeyPaths mocks base method
func (m *MockKeyPathFunc) ReferencedKeyPaths() []string {
	ret := m.ctrl.Call(m, "ReferencedKeyPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ReferencedKeyPaths indicates an expected call of ReferencedKeyPaths
func (mr *MockKeyPathFuncMockRecorder) ReferencedKeyPaths() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReferencedKeyPaths", reflect.TypeOf((*MockKeyPathFunc)(nil).ReferencedKeyPaths))
}

// MockVisitor is a mock of Visitor interface
type MockVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockVisitorMockRecorder
}

// MockVisitorMockRecorder is the mock recorder for MockVisitor
type MockVisitorMockRecorder struct {
	mock *MockVisitor
}

// NewMockVisitor creates a new mock instance
func NewMockVisitor(ctrl *gomock.Controller) *MockVisitor {
	mock := &MockVisitor{ctrl: ctrl}
	mock.recorder = &MockVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVisitor) EXPECT() *MockVisitorMockRecorder {
	return m.recorder
}

// MockFullQueryVisitor is a mock of FullQueryVisitor interface
type MockFullQueryVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockFullQueryVisitorMockRecorder
}

// MockFullQueryVisitorMockRecorder is the mock recorder for MockFullQueryVisitor
type MockFullQueryVisitorMockRecorder struct {
	mock *MockFullQueryVisitor
}

// NewMockFullQueryVisitor creates a new mock instance
func NewMockFullQueryVisitor(ctrl *gomock.Controller) *MockFullQueryVisitor {
	mock := &MockFullQueryVisitor{ctrl: ctrl}
	mock.recorder = &MockFullQueryVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockFullQueryVisitor) EXPECT() *MockFullQueryVisitorMockRecorder {
	return m.recorder
}

// VisitQuery mocks base method
func (m *MockFullQueryVisitor) VisitQuery(arg0 Query) {
	m.ctrl.Call(m, "VisitQuery", arg0)
}

// VisitQuery indicates an expected call of VisitQuery
func (mr *MockFullQueryVisitorMockRecorder) VisitQuery(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitQuery", reflect.TypeOf((*MockFullQueryVisitor)(nil).VisitQuery), arg0)
}

// EndVisitQuery mocks base method
func (m *MockFullQueryVisitor) EndVisitQuery(arg0 Query) {
	m.ctrl.Call(m, "EndVisitQuery", arg0)
}

// EndVisitQuery indicates an expected call of EndVisitQuery
func (mr *MockFullQueryVisitorMockRecorder) EndVisitQuery(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitQuery", reflect.TypeOf((*MockFullQueryVisitor)(nil).EndVisitQuery), arg0)
}

// VisitPredicate mocks base method
func (m *MockFullQueryVisitor) VisitPredicate(arg0 Predicate) {
	m.ctrl.Call(m, "VisitPredicate", arg0)
}

// VisitPredicate indicates an expected call of VisitPredicate
func (mr *MockFullQueryVisitorMockRecorder) VisitPredicate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitPredicate", reflect.TypeOf((*MockFullQueryVisitor)(nil).VisitPredicate), arg0)
}

// EndVisitPredicate mocks base method
func (m *MockFullQueryVisitor) EndVisitPredicate(arg0 Predicate) {
	m.ctrl.Call(m, "EndVisitPredicate", arg0)
}

// EndVisitPredicate indicates an expected call of EndVisitPredicate
func (mr *MockFullQueryVisitorMockRecorder) EndVisitPredicate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitPredicate", reflect.TypeOf((*MockFullQueryVisitor)(nil).EndVisitPredicate), arg0)
}

// VisitSort mocks base method
func (m *MockFullQueryVisitor) VisitSort(arg0 Sort) {
	m.ctrl.Call(m, "VisitSort", arg0)
}

// VisitSort indicates an expected call of VisitSort
func (mr *MockFullQueryVisitorMockRecorder) VisitSort(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitSort", reflect.TypeOf((*MockFullQueryVisitor)(nil).VisitSort), arg0)
}

// EndVisitSort mocks base method
func (m *MockFullQueryVisitor) EndVisitSort(arg0 Sort) {
	m.ctrl.Call(m, "EndVisitSort", arg0)
}

// EndVisitSort indicates an expected call of EndVisitSort
func (mr *MockFullQueryVisitorMockRecorder) EndVisitSort(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitSort", reflect.TypeOf((*MockFullQueryVisitor)(nil).EndVisitSort), arg0)
}

// VisitExpression mocks base method
func (m *MockFullQueryVisitor) VisitExpression(arg0 Expression) {
	m.ctrl.Call(m, "VisitExpression", arg0)
}

// VisitExpression indicates an expected call of VisitExpression
func (mr *MockFullQueryVisitorMockRecorder) VisitExpression(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitExpression", reflect.TypeOf((*MockFullQueryVisitor)(nil).VisitExpression), arg0)
}

// EndVisitExpression mocks base method
func (m *MockFullQueryVisitor) EndVisitExpression(arg0 Expression) {
	m.ctrl.Call(m, "EndVisitExpression", arg0)
}

// EndVisitExpression indicates an expected call of EndVisitExpression
func (mr *MockFullQueryVisitorMockRecorder) EndVisitExpression(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitExpression", reflect.TypeOf((*MockFullQueryVisitor)(nil).EndVisitExpression), arg0)
}

// MockQueryVisitor is a mock of QueryVisitor interface
type MockQueryVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockQueryVisitorMockRecorder
}

// MockQueryVisitorMockRecorder is the mock recorder for MockQueryVisitor
type MockQueryVisitorMockRecorder struct {
	mock *MockQueryVisitor
}

// NewMockQueryVisitor creates a new mock instance
func NewMockQueryVisitor(ctrl *gomock.Controller) *MockQueryVisitor {
	mock := &MockQueryVisitor{ctrl: ctrl}
	mock.recorder = &MockQueryVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQueryVisitor) EXPECT() *MockQueryVisitorMockRecorder {
	return m.recorder
}

// VisitQuery mocks base method
func (m *MockQueryVisitor) VisitQuery(arg0 Query) {
	m.ctrl.Call(m, "VisitQuery", arg0)
}

// VisitQuery indicates an expected call of VisitQuery
func (mr *MockQueryVisitorMockRecorder) VisitQuery(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitQuery", reflect.TypeOf((*MockQueryVisitor)(nil).VisitQuery), arg0)
}

// EndVisitQuery mocks base method
func (m *MockQueryVisitor) EndVisitQuery(arg0 Query) {
	m.ctrl.Call(m, "EndVisitQuery", arg0)
}

// EndVisitQuery indicates an expected call of EndVisitQuery
func (mr *MockQueryVisitorMockRecorder) EndVisitQuery(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitQuery", reflect.TypeOf((*MockQueryVisitor)(nil).EndVisitQuery), arg0)
}

// MockPredicateVisitor is a mock of PredicateVisitor interface
type MockPredicateVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockPredicateVisitorMockRecorder
}

// MockPredicateVisitorMockRecorder is the mock recorder for MockPredicateVisitor
type MockPredicateVisitorMockRecorder struct {
	mock *MockPredicateVisitor
}

// NewMockPredicateVisitor creates a new mock instance
func NewMockPredicateVisitor(ctrl *gomock.Controller) *MockPredicateVisitor {
	mock := &MockPredicateVisitor{ctrl: ctrl}
	mock.recorder = &MockPredicateVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPredicateVisitor) EXPECT() *MockPredicateVisitorMockRecorder {
	return m.recorder
}

// VisitPredicate mocks base method
func (m *MockPredicateVisitor) VisitPredicate(arg0 Predicate) {
	m.ctrl.Call(m, "VisitPredicate", arg0)
}

// VisitPredicate indicates an expected call of VisitPredicate
func (mr *MockPredicateVisitorMockRecorder) VisitPredicate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitPredicate", reflect.TypeOf((*MockPredicateVisitor)(nil).VisitPredicate), arg0)
}

// EndVisitPredicate mocks base method
func (m *MockPredicateVisitor) EndVisitPredicate(arg0 Predicate) {
	m.ctrl.Call(m, "EndVisitPredicate", arg0)
}

// EndVisitPredicate indicates an expected call of EndVisitPredicate
func (mr *MockPredicateVisitorMockRecorder) EndVisitPredicate(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitPredicate", reflect.TypeOf((*MockPredicateVisitor)(nil).EndVisitPredicate), arg0)
}

// MockSortVisitor is a mock of SortVisitor interface
type MockSortVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockSortVisitorMockRecorder
}

// MockSortVisitorMockRecorder is the mock recorder for MockSortVisitor
type MockSortVisitorMockRecorder struct {
	mock *MockSortVisitor
}

// NewMockSortVisitor creates a new mock instance
func NewMockSortVisitor(ctrl *gomock.Controller) *MockSortVisitor {
	mock := &MockSortVisitor{ctrl: ctrl}
	mock.recorder = &MockSortVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSortVisitor) EXPECT() *MockSortVisitorMockRecorder {
	return m.recorder
}

// VisitSort mocks base method
func (m *MockSortVisitor) VisitSort(arg0 Sort) {
	m.ctrl.Call(m, "VisitSort", arg0)
}

// VisitSort indicates an expected call of VisitSort
func (mr *MockSortVisitorMockRecorder) VisitSort(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitSort", reflect.TypeOf((*MockSortVisitor)(nil).VisitSort), arg0)
}

// EndVisitSort mocks base method
func (m *MockSortVisitor) EndVisitSort(arg0 Sort) {
	m.ctrl.Call(m, "EndVisitSort", arg0)
}

// EndVisitSort indicates an expected call of EndVisitSort
func (mr *MockSortVisitorMockRecorder) EndVisitSort(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitSort", reflect.TypeOf((*MockSortVisitor)(nil).EndVisitSort), arg0)
}

// MockExpressionVisitor is a mock of ExpressionVisitor interface
type MockExpressionVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockExpressionVisitorMockRecorder
}

// MockExpressionVisitorMockRecorder is the mock recorder for MockExpressionVisitor
type MockExpressionVisitorMockRecorder struct {
	mock *MockExpressionVisitor
}

// NewMockExpressionVisitor creates a new mock instance
func NewMockExpressionVisitor(ctrl *gomock.Controller) *MockExpressionVisitor {
	mock := &MockExpressionVisitor{ctrl: ctrl}
	mock.recorder = &MockExpressionVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExpressionVisitor) EXPECT() *MockExpressionVisitorMockRecorder {
	return m.recorder
}

// VisitExpression mocks base method
func (m *MockExpressionVisitor) VisitExpression(arg0 Expression) {
	m.ctrl.Call(m, "VisitExpression", arg0)
}

// VisitExpression indicates an expected call of VisitExpression
func (mr *MockExpressionVisitorMockRecorder) VisitExpression(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VisitExpression", reflect.TypeOf((*MockExpressionVisitor)(nil).VisitExpression), arg0)
}

// EndVisitExpression mocks base method
func (m *MockExpressionVisitor) EndVisitExpression(arg0 Expression) {
	m.ctrl.Call(m, "EndVisitExpression", arg0)
}

// EndVisitExpression indicates an expected call of EndVisitExpression
func (mr *MockExpressionVisitorMockRecorder) EndVisitExpression(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndVisitExpression", reflect.TypeOf((*MockExpressionVisitor)(nil).EndVisitExpression), arg0)
}
