apiVersion: v1
kind: Namespace
metadata:
  name: authgear
---
apiVersion: v1
kind: Secret
metadata:
  namespace: authgear
  name: app-accounts
  labels:
    authgear.com/app-id: accounts
stringData:
  authgear.yaml: |-
    id: accounts
    http:
      public_origin: 'http://accounts.portal.localhost:3000'
      allowed_origins:
        - '*'
    session:
      cookie_domain: .portal.localhost
    oauth:
      clients:
        - name: Portal
          client_id: portal
          grant_types: []
          post_logout_redirect_uris:
            - 'http://portal.localhost:8000/oauth-redirect'
          redirect_uris:
            - 'http://portal.localhost:8000/oauth-redirect'
          response_types:
            - none
    authentication:
      identities:
        - login_id
        - oauth
      primary_authenticators:
        - password
      secondary_authenticators:
        - totp
      secondary_authentication_mode: if_exists
    identity:
      login_id:
        keys:
          - key: email
            type: email
    verification:
      claims:
        email:
          required: false
  authgear.secrets.yaml: |-
    secrets:
      - data:
          keys:
            - alg: RS256
              d: >-
                eHqanKqakSpJXg9hMUeq--AJoXuLOYmm58p5FdvbsvSW3FJsG4mziCma6Lq9w0iQMM2UHvWSYVQF3F9oBwfYhOMcPdU3hCGVyScOujtEJ71UvvP09ADt2KZsC7WxY4Qg4iy_X2BVVsiI1L0C79i6HO-ZBau-LC06H9vhpOLZjP70Y4o0moOqk925WWcaxG-mlrYyVz2waSagwWQ_1dtYM2WMIXVakYy_GGRKYCEMzatNhqb1dPSDxDWvI7O_sEyUFdWAH5lCjpBWugizlUwTcJCsBV-d9sY7Ux0GnE_xopbhqth-R_Ofyd1Y8vMltyrJ_ZvUOwlnpiNlb2cmyUntSQ
              dp: >-
                Pkl4YQsHSmn03G-Gn445b45RzQhoaJAdS-_zMLWk5LK3gPt4F3aHPBrizKPg2R6DpW2rpoKjZitiF6t6CiNdmB9w1rxSbPNOOqowaxtX_pwlddGFPRRbHANC6Ahq-2GQ-vkXJWZFpcRhz00QNQ4ACGcCREJQ7RBsx_RDg8uwJ60
              dq: >-
                SZO7pBgAzinKHfeI8pq4mah8wTTS7w4c92zrgI1aTHs5rXa_8MbROpaBl2gzKieq0762Ng3pKa_wqsfeLABdykEaXKgTaFWd-ModYk4ClEdCUFTbbv9XPs-AD8eO7DHJqXZBO2PJDNTdz3XNxCQhJr7FG8Vjih0kKlVYJkqxfZM
              e: AQAB
              kid: 11213ade-9da7-4950-991f-cfd3730c5bf7
              kty: RSA
              'n': >-
                vju_dLCKuW75Wm_HwP7HyLS5ry9DDOu18jejiN5xzPULfXLCqtWF3V5l-u2MjTUNUYljC6rkkj2ZS-iW7af-y669gTlbOtXJhLLqEB9fKaqXbuOEP9X4x_YP08zQbd6ySa2VUqJXKFx3C8q1Vo585UE0nnenbh2rPJejVwfMfFo1i8gm1GFbzYkPxx4pMczT4mysXI1UPAv6InFlfCfeu-oO0za2e3Th0EfLs3V550KRQcU3f65ct1PvSVrs-b9DL6lG_OyUTflPKTVxZ2ZDPps0NKCs_7-uTVVHLoX05gC7vDBSBUs2us0lAyLQoe72WHmXlHL68_SHiXHkq-PwMQ
              p: >-
                yzDWnk6m5W9I_rSGpxewQO73tYJTJT2fKA2mJa2MyQXwzpIlgDL0O93V8XTef-CPlWLfDL8P8EkYYJv97ke2V0ZgkOye1zhWa5q1rQRLqlH2MA1krLV1Ni--5slSSh5H-jc6ayiI9WYDJ_jbm8TWQps9VXWuSUMTTBZEdE4JEI8
              q: >-
                76zMc6JCRS1DjNc69BK4VDKfWujhujU2mBRLWLY_hH3ycdZBukfQ4xmKOQ2VhxQ0uNPB0DwMdvXwiVPNM_XK3wrwITdJsQvMn958hnZsaiTbaZadS7trTk1S6j_Vf2rYEwjTpr1ERg8S39C7bZfN9CpYNi-1ErNdeoqZX7xN0z8
              qi: >-
                dHSYRtduUNHeWjhqW_XrWmBDAnZSSCQeXa04VHpgNdegjHk2ZbJ5kbHsvxMIRqMfE9bpy4IYYeAdcBc3Vqvx5fL-1HSkzOnn-fVUJBEcV7_gCi2GUMWbJeBjUuFEQDNBmksfnGz_IpZfXkXxql9tqSQvVJnJ2t1L9PQH5RS3HKs
        key: oidc
      - data:
          keys:
            - k: Jp5uzkj5cIGdhwD8zEc62s-Hfgkmc-3Ng0F2lmCcNn4
              kid: 3c307a63-9e6b-4487-805d-bc161eb859f8
              kty: oct
        key: csrf
      - data:
          keys:
            - k: qB496DGCUsClLKI7mlV8Bnx9A2ic4hfgoFCizw08Xtw
              kid: 2fcd3cda-38b2-4826-a6d4-ca339454d029
              kty: oct
        key: webhook
      - data:
          keys:
            - alg: RS256
              d: >-
                eHqanKqakSpJXg9hMUeq--AJoXuLOYmm58p5FdvbsvSW3FJsG4mziCma6Lq9w0iQMM2UHvWSYVQF3F9oBwfYhOMcPdU3hCGVyScOujtEJ71UvvP09ADt2KZsC7WxY4Qg4iy_X2BVVsiI1L0C79i6HO-ZBau-LC06H9vhpOLZjP70Y4o0moOqk925WWcaxG-mlrYyVz2waSagwWQ_1dtYM2WMIXVakYy_GGRKYCEMzatNhqb1dPSDxDWvI7O_sEyUFdWAH5lCjpBWugizlUwTcJCsBV-d9sY7Ux0GnE_xopbhqth-R_Ofyd1Y8vMltyrJ_ZvUOwlnpiNlb2cmyUntSQ
              dp: >-
                Pkl4YQsHSmn03G-Gn445b45RzQhoaJAdS-_zMLWk5LK3gPt4F3aHPBrizKPg2R6DpW2rpoKjZitiF6t6CiNdmB9w1rxSbPNOOqowaxtX_pwlddGFPRRbHANC6Ahq-2GQ-vkXJWZFpcRhz00QNQ4ACGcCREJQ7RBsx_RDg8uwJ60
              dq: >-
                SZO7pBgAzinKHfeI8pq4mah8wTTS7w4c92zrgI1aTHs5rXa_8MbROpaBl2gzKieq0762Ng3pKa_wqsfeLABdykEaXKgTaFWd-ModYk4ClEdCUFTbbv9XPs-AD8eO7DHJqXZBO2PJDNTdz3XNxCQhJr7FG8Vjih0kKlVYJkqxfZM
              e: AQAB
              kid: 11213ade-9da7-4950-991f-cfd3730c5bf7
              kty: RSA
              'n': >-
                vju_dLCKuW75Wm_HwP7HyLS5ry9DDOu18jejiN5xzPULfXLCqtWF3V5l-u2MjTUNUYljC6rkkj2ZS-iW7af-y669gTlbOtXJhLLqEB9fKaqXbuOEP9X4x_YP08zQbd6ySa2VUqJXKFx3C8q1Vo585UE0nnenbh2rPJejVwfMfFo1i8gm1GFbzYkPxx4pMczT4mysXI1UPAv6InFlfCfeu-oO0za2e3Th0EfLs3V550KRQcU3f65ct1PvSVrs-b9DL6lG_OyUTflPKTVxZ2ZDPps0NKCs_7-uTVVHLoX05gC7vDBSBUs2us0lAyLQoe72WHmXlHL68_SHiXHkq-PwMQ
              p: >-
                yzDWnk6m5W9I_rSGpxewQO73tYJTJT2fKA2mJa2MyQXwzpIlgDL0O93V8XTef-CPlWLfDL8P8EkYYJv97ke2V0ZgkOye1zhWa5q1rQRLqlH2MA1krLV1Ni--5slSSh5H-jc6ayiI9WYDJ_jbm8TWQps9VXWuSUMTTBZEdE4JEI8
              q: >-
                76zMc6JCRS1DjNc69BK4VDKfWujhujU2mBRLWLY_hH3ycdZBukfQ4xmKOQ2VhxQ0uNPB0DwMdvXwiVPNM_XK3wrwITdJsQvMn958hnZsaiTbaZadS7trTk1S6j_Vf2rYEwjTpr1ERg8S39C7bZfN9CpYNi-1ErNdeoqZX7xN0z8
              qi: >-
                dHSYRtduUNHeWjhqW_XrWmBDAnZSSCQeXa04VHpgNdegjHk2ZbJ5kbHsvxMIRqMfE9bpy4IYYeAdcBc3Vqvx5fL-1HSkzOnn-fVUJBEcV7_gCi2GUMWbJeBjUuFEQDNBmksfnGz_IpZfXkXxql9tqSQvVJnJ2t1L9PQH5RS3HKs
        key: admin-api.auth
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: authgear
  name: accounts.portal.localhost
  labels:
    authgear.com/app-id: accounts
spec:
  rules:
    - host: accounts.portal.localhost
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: authgear
  name: admin.accounts.portal.localhost
  labels:
    authgear.com/app-id: accounts
spec:
  rules:
    - host: admin.accounts.portal.localhost
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: authgear
  name: admin.accounts.localhost
  labels:
    authgear.com/app-id: accounts
spec:
  rules:
    - host: admin.accounts.localhost
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: authgear
  name: portal.localhost
  labels:
    authgear.com/app-id: accounts
spec:
  rules:
    - host: portal.localhost
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: authgear
  name: accounts.localhost
  labels:
    authgear.com/app-id: accounts
spec:
  rules:
    - host: accounts.localhost
#---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  namespace: authgear
#  name: letsencrypt-staging
#spec:
#  acme:
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    email: authgear@example.com
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    solvers:
#      - selector: {}
#        http01:
#          ingress:
#            class: nginx
