query dynamicClientsQuery(
  $first: Int
  $after: String
  $source: OAuthClientSource
) {
  dynamicClients(first: $first, after: $after, source: $source) {
    edges {
      node {
        id
        clientID
        clientName
        name
        kind
        source
        registeredAt
        lastFetchedAt
        applicationType
        redirectURIs
        grantTypes
        responseTypes
        logoURI
        clientURI
        tosURI
        policyURI
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
    }
    totalCount
  }
}
