import * as _1 from "@apollo/client";
console.log(_1);
import * as _2 from "@authgear/web";
console.log(_2);
import * as _3 from "@elgorditosalsero/react-gtm-hook";
console.log(_3);
import * as _4 from "@fluentui/merge-styles";
console.log(_4);
import * as _5 from "@fluentui/react";
console.log(_5);
import * as _6 from "@fluentui/react-hooks";
console.log(_6);
import * as _7 from "@fluentui/react-icons";
console.log(_7);
import * as _8 from "@monaco-editor/react";
console.log(_8);
import * as _9 from "@oursky/react-messageformat";
console.log(_9);
import * as _10 from "@sentry/react";
console.log(_10);
import * as _11 from "@tabler/icons";
console.log(_11);
import * as _12 from "axios";
console.log(_12);
import * as _13 from "base64-js";
console.log(_13);
import * as _14 from "bignumber.js";
console.log(_14);
import * as _15 from "chart.js";
console.log(_15);
import * as _16 from "chartjs-plugin-datalabels";
console.log(_16);
import * as _17 from "classnames";
console.log(_17);
import * as _18 from "cropperjs";
console.log(_18);
import _19 from "deep-equal";
console.log(_19);
import * as _20 from "history";
console.log(_20);
import * as _21 from "immer";
console.log(_21);
import * as _22 from "intl-tel-input";
console.log(_22);
import * as _23 from "js-yaml";
console.log(_23);
import * as _24 from "luxon";
console.log(_24);
import * as _25 from "monaco-editor";
console.log(_25);
import * as _26 from "postcss";
console.log(_26);
import * as _27 from "react";
console.log(_27);
import * as _28 from "react-chartjs-2";
console.log(_28);
import * as _29 from "react-dom";
console.log(_29);
import * as _30 from "react-helmet-async";
console.log(_30);
import * as _31 from "react-router-dom";
console.log(_31);
import * as _32 from "tzdata";
console.log(_32);
import * as _33 from "uuid";
console.log(_33);
import * as _34 from "zxcvbn";
console.log(_34);
