package intl

import (
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

func TestResolveCloudflareTurnstile(t *testing.T) {
	Convey("ResolveCloudflareTurnstile", t, func() {
		test := func(target string, expected string) {
			actual := ResolveCloudflareTurnstile(target)
			So(actual, ShouldEqual, expected)
			So(CloudflareTurnstileLanguages, ShouldContain, actual)
		}

		// authgear-supported, non-turnstile-supported
		test("es-ES", "es-ES")
		test("fil", "tl-PH")
		test("be", "ru")
		test("eu", "fr")
		test("bn", "en")
		test("ka", "ru")
		test("hy", "ru")
		test("kn", "hi")
		test("ta", "hi")
		test("km", "en")
		test("lv", "ru")
		test("si", "en")
		test("zu", "en")
		test("ne", "en")
		test("sw", "en")
		test("mn", "en")
		test("gl", "es")
		test("pt-PT", "pt")
		test("no", "en")
		test("ky", "ru")
		test("az", "ru")
		test("ml", "hi")
		test("ca", "es")
		test("te", "hi")
		test("zh-HK", "zh-TW")
		test("is", "en")
		test("et", "en")
		test("af", "en")
		test("lo", "en")
		test("mr", "hi")
		test("my", "en")
		test("mk", "tr")
		test("am", "en")
		test("es-419", "es")
		// both authgear- & turnstile-supported
		test("fi", "fi")
		test("th", "th")
		test("fa", "fa")
		test("ja", "ja")
		test("ms", "ms")
		test("sr", "sr")
		test("sl", "sl")
		test("pt", "pt")
		test("nl", "nl")
		test("es", "es")
		test("id", "id")
		test("hu", "hu")
		test("ro", "ro")
		test("zh-CN", "zh-CN")
		test("ar", "ar")
		test("bg", "bg")
		test("hr", "hr")
		test("ru", "ru")
		test("de", "de")
		test("en", "en")
		test("cs", "cs")
		test("da", "da")
		test("sv", "sv")
		test("fr", "fr")
		test("ko", "ko")
		test("pt-BR", "pt-BR")
		test("hi", "hi")
		test("lt", "lt")
		test("pl", "pl")
		test("el", "el")
		test("it", "it")
		test("zh-TW", "zh-TW")
		test("tr", "tr")
		test("uk", "uk")
		test("vi", "vi")
		test("es-ES", "es-ES")
		test("sk", "sk")
	})
}
