# @no-cookie-jar

{{+
exports.headers = {
'Content-Type': 'application/json',
'Cookie': `session=${SESSION_COOKIE}`
};
}}

{{+response
$global.workflow_id = response.parsedBody?.result?.workflow?.workflow_id ?? $global.workflow_id;
$global.instance_id = response.parsedBody?.result?.workflow?.instance_id ?? $global.instance_id;
}}


###
# @name start
POST {{HOST}}/api/v1/workflows
...headers

{
    "intent": {
        "kind": "latte.IntentVerifyUser",
        "data": {}
    }
}


###
# @name get
GET {{HOST}}/api/v1/workflows/{{$global.workflow_id}}/instances/{{$global.instance_id}}
...headers


###
# @name trigger
POST {{HOST}}/api/v1/workflows/{{$global.workflow_id}}/instances/{{$global.instance_id}}
...headers

// "method": "email", "sms"
// "claim_name": "email", "phone_number"

{
    "input": {
        "kind": "latte.InputTriggerVerification",
        "data": {
            "method": "",
            "claim_name": "",
            "claim_value": ""
        }
    }
}

###
# @name resend_code
POST {{HOST}}/api/v1/workflows/{{$global.workflow_id}}/instances/{{$global.instance_id}}
...headers

{
    "input": {
        "kind": "latte.InputOTPVerificationResend",
        "data": {
        }
    }
}


###
# @name enter_otp
POST {{HOST}}/api/v1/workflows/{{$global.workflow_id}}/instances/{{$global.instance_id}}
...headers

{
    "input": {
        "kind": "latte.InputOTPVerification",
        "data": {
            "code": ""
        }
    }
}
