name: Build custom image
description: "Build custom image and upload to GCP"
inputs:
  dockerfile:
    description: "The path to Dockerfile"
    required: true
  image_name:
    description: "The full image name"
    required: true
  gcp_project_id:
    description: "Forwarded input to google-github-actions-auth"
    required: true
  gcp_workload_identity_provider:
    description: "Forwarded input to google-github-actions-auth"
    required: true
  docker_repo:
    description: "Forwarded input to google-github-actions-setup-gcloud"
    required: false
runs:
  using: "composite"
  steps:
  - uses: oursky/google-github-actions-auth@v2
    with:
      project_id: ${{ inputs.gcp_project_id }}
      workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
  - uses: oursky/google-github-actions-setup-gcloud@v2
  - name: Configure docker
    env:
      REPO: ${{ inputs.docker_repo }}
    shell: bash
    run: |
      gcloud auth configure-docker "$REPO"
  - name: Build and Push
    env:
      DOCKERFILE: ${{ inputs.dockerfile }}
      IMAGE_NAME: ${{ inputs.image_name }}
      BUILD_ARCH: amd64
      EXTRA_BUILD_OPTS: '--ssh=default'
      OUTPUT: ${{ format('type=image,name={0},push-by-digest=true,name-canonical=true,push=true', inputs.image_name) }}
    shell: bash
    run: |
      export METADATA_FILE="$(mktemp).json"
      echo "METADATA_FILE=$METADATA_FILE"
      make -C custombuild build-image
      (set -x && cat "$METADATA_FILE")
      export SOURCE_DIGESTS="$(jq < "$METADATA_FILE" '.["containerimage.digest"]' -r)"
      make -C custombuild tag-image
  - name: docker logout
    if: ${{ always() }}
    env:
      REPO: ${{ inputs.docker_repo }}
    shell: bash
    run: |
      docker logout "$REPO"
