name: Run checks

on:
  workflow_call:

jobs:
  authui-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./.tool-versions"
    - run: npm ci
      working-directory: ./authui
    - name: Run npm audit
      env:
        AUDIT_LEVEL: high
      run: |
        if [ -z "${AUDIT_LEVEL}" ]; then
          npm audit
        else
          npm audit --audit-level="${AUDIT_LEVEL}"
        fi
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run typecheck
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run eslint
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run stylelint
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run prettier
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run test
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: make check-tidy
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run build
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run ensure-reproducible-build
      working-directory: ./authui
      if: ${{ !cancelled() }}
    - run: npm run browserslist-coverage-lint
      working-directory: ./authui
      if: ${{ !cancelled() }}

  portal-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-native-deps
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./.tool-versions"
    - run: npm ci
      working-directory: ./portal
    - name: Run npm audit
      env:
        AUDIT_LEVEL: high
      run: |
        if [ -z "${AUDIT_LEVEL}" ]; then
          npm audit
        else
          npm audit --audit-level="${AUDIT_LEVEL}"
        fi
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run typecheck
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run eslint
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run stylelint
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run prettier
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run test
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run gentype
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: make check-tidy
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run build
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run ensure-reproducible-build
      working-directory: ./portal
      if: ${{ !cancelled() }}
    - run: npm run browserslist-coverage-lint
      working-directory: ./portal
      if: ${{ !cancelled() }}


  authgear-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/install-native-deps
    - uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"
    - uses: actions/setup-node@v4
      with:
        node-version-file: "./.tool-versions"
    - run: make vendor
    - run: npm ci
      working-directory: ./scripts/npm
    - run: make check-dockerignore
      if: ${{ !cancelled() }}
    - run: make govulncheck
      if: ${{ !cancelled() }}
    # We cannot enable this until we move to mjml@5
    # https://github.com/mjmlio/mjml/issues/2589
    #- run: npm audit
    #  working-directory: ./scripts/npm
    #  if: ${{ !cancelled() }}
    - run: make ensure-important-modules-up-to-date
      if: ${{ !cancelled() }}
    - run: make lint
      if: ${{ !cancelled() }}
    - run: make test
      if: ${{ !cancelled() }}
    - run: make fmt
      if: ${{ !cancelled() }}
    - run: make check-tidy
      if: ${{ !cancelled() }}
    - run: make check-spell-translations
      if: ${{ !cancelled() }}
    - run: make -C packagetracker check-if-new-version-available
      if: ${{ !cancelled() }}

  authgear-e2e:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/docker-buildx-create
    - uses: ./.github/actions/install-native-deps
    - uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"
    - run: make vendor
    - uses: actions/cache/restore@v4
      id: cache
      with:
        path: ./e2e/docker-compose-build-cache
        key: ${{ runner.environment }}-${{ runner.os }}-${{ runner.arch }}-e2e-docker-compose-build-cache
    - run: make -C e2e docker-compose-build
    - uses: actions/cache/save@v4
      with:
        path: ./e2e/docker-compose-build-cache
        key: ${{ steps.cache.outputs.cache-primary-key }}
    - run: make -C e2e ci
      if: ${{ !cancelled() }}
      env:
        COMPOSE_INTERACTIVE_NO_CLI: 1

  k6:
    runs-on: ubuntu-24.04
    # Disable the job as it always fails
    if: ${{ false }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/docker-buildx-create
    - uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"
    - run: make vendor
    - uses: actions/cache/restore@v4
      id: cache
      with:
        path: ./k6/docker-compose-build-cache
        key: ${{ runner.environment }}-${{ runner.os }}-${{ runner.arch }}-k6-docker-compose-build-cache
    - run: make -C k6 all
    - uses: actions/cache/save@v4
      with:
        path: ./k6/docker-compose-build-cache
        key: ${{ steps.cache.outputs.cache-primary-key }}
