// Code generated by MockGen. DO NOT EDIT.
// Source: userinfo.go

// Package userinfo is a generated GoMock package.
package userinfo

import (
	context "context"
	reflect "reflect"

	model "github.com/authgear/authgear-server/pkg/api/model"
	authenticator "github.com/authgear/authgear-server/pkg/lib/authn/authenticator"
	accesscontrol "github.com/authgear/authgear-server/pkg/util/accesscontrol"
	gomock "github.com/golang/mock/gomock"
)

// MockRolesAndGroupsQueries is a mock of RolesAndGroupsQueries interface.
type MockRolesAndGroupsQueries struct {
	ctrl     *gomock.Controller
	recorder *MockRolesAndGroupsQueriesMockRecorder
}

// MockRolesAndGroupsQueriesMockRecorder is the mock recorder for MockRolesAndGroupsQueries.
type MockRolesAndGroupsQueriesMockRecorder struct {
	mock *MockRolesAndGroupsQueries
}

// NewMockRolesAndGroupsQueries creates a new mock instance.
func NewMockRolesAndGroupsQueries(ctrl *gomock.Controller) *MockRolesAndGroupsQueries {
	mock := &MockRolesAndGroupsQueries{ctrl: ctrl}
	mock.recorder = &MockRolesAndGroupsQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolesAndGroupsQueries) EXPECT() *MockRolesAndGroupsQueriesMockRecorder {
	return m.recorder
}

// ListEffectiveRolesByUserID mocks base method.
func (m *MockRolesAndGroupsQueries) ListEffectiveRolesByUserID(ctx context.Context, userID string) ([]*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEffectiveRolesByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEffectiveRolesByUserID indicates an expected call of ListEffectiveRolesByUserID.
func (mr *MockRolesAndGroupsQueriesMockRecorder) ListEffectiveRolesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEffectiveRolesByUserID", reflect.TypeOf((*MockRolesAndGroupsQueries)(nil).ListEffectiveRolesByUserID), ctx, userID)
}

// MockUserInfoAuthenticatorService is a mock of UserInfoAuthenticatorService interface.
type MockUserInfoAuthenticatorService struct {
	ctrl     *gomock.Controller
	recorder *MockUserInfoAuthenticatorServiceMockRecorder
}

// MockUserInfoAuthenticatorServiceMockRecorder is the mock recorder for MockUserInfoAuthenticatorService.
type MockUserInfoAuthenticatorServiceMockRecorder struct {
	mock *MockUserInfoAuthenticatorService
}

// NewMockUserInfoAuthenticatorService creates a new mock instance.
func NewMockUserInfoAuthenticatorService(ctrl *gomock.Controller) *MockUserInfoAuthenticatorService {
	mock := &MockUserInfoAuthenticatorService{ctrl: ctrl}
	mock.recorder = &MockUserInfoAuthenticatorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInfoAuthenticatorService) EXPECT() *MockUserInfoAuthenticatorServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockUserInfoAuthenticatorService) List(ctx context.Context, userID string, filters ...authenticator.Filter) ([]*authenticator.Info, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, userID}
	for _, a := range filters {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].([]*authenticator.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserInfoAuthenticatorServiceMockRecorder) List(ctx, userID interface{}, filters ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, userID}, filters...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserInfoAuthenticatorService)(nil).List), varargs...)
}

// MockUserQueries is a mock of UserQueries interface.
type MockUserQueries struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueriesMockRecorder
}

// MockUserQueriesMockRecorder is the mock recorder for MockUserQueries.
type MockUserQueriesMockRecorder struct {
	mock *MockUserQueries
}

// NewMockUserQueries creates a new mock instance.
func NewMockUserQueries(ctrl *gomock.Controller) *MockUserQueries {
	mock := &MockUserQueries{ctrl: ctrl}
	mock.recorder = &MockUserQueriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueries) EXPECT() *MockUserQueriesMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserQueries) Get(ctx context.Context, id string, role accesscontrol.Role) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id, role)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserQueriesMockRecorder) Get(ctx, id, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserQueries)(nil).Get), ctx, id, role)
}
